services:
  mongo:
    image: mongo:7
    container_name: day2-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  server:
    build: ./server
    container_name: day2-server
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/appdb
    depends_on:
      - mongo
    ports:
      - "5001:5000"   # host 5001 -> container 5000
    networks:
      - appnet

  client:
    build: ./client
    container_name: day2-client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "5173:80"     # host 5173 -> container 80
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
